### PR TITLE
Working on some design features

### PR DESCRIPTION
**Pull request by DRFR0ST**
Hi! I've been working on the aesthetics for a little. Added a 3d model of earth and some colors. What do you think? 

:warning: This needs some testing since performance might be dropping on model load.

ℹ️ I'm also working on showing a satellite for each commit made in our projects. This can be found on branch **feat/push-orbit**.

image

### CODE REVIEW

**Comment by DRFR0ST** [comment]
⚡️ Deploying PR Preview b26d589143b3d2c45fa0ac5ce108038f804041a6 to [surge.sh](https://Assembless-assembless-tech-build-pr-7.surge.sh) ... [Build logs](https://github.com/Assembless/assembless.tech/runs/1899593958)

<a href="https://github.com/Assembless/assembless.tech/runs/1899593958"></a>

<sub>🤖 By [surge-preview](https://github.com/afc163/surge-preview)</sub>

**Comment by norwegianbegginer** [comment]
hi Mike i made some changes in the console, so these are not so big. Logo is in img so it was to hard to set it in the same column as h1. I used also linear gradient on circle to imitate moon and some styling things. Btw good job!
Screenshot (8)

**Comment by DRFR0ST** [comment]
> hi Mike i made some changes in the console, so these are not so big. Logo is in img so it was to hard to set it in the same column as h1. I used also linear gradient on circle to imitate moon and some styling things. Btw good job!

Can you please send me the changes listed so I can apply it? Or push a commit with these changes please.

**Comment by DRFR0ST** [comment]
Got feedback about commits around the orbit of the earth. Maybe a better idea would be to put a satellite for each active visitor?

**Comment by norwegianbegginer** [comment]
Yep, this is of course good idea, a moon was only to temporary fix that white circle.  I would consider removing white border from container, i just dont feel it, and with satelites should give good effect.

**Comment by DRFR0ST** [comment]
Are you willing to work on the style? 😁

**Comment by DRFR0ST** [comment]
The cost of including the 3d earth is huge.

With 3d earth:
image

Without 3d earth:
image

**Comment by DRFR0ST** [comment]
⚡️ Deploying PR Preview 1308ec2c09cfb278478320a0d25be0e0cb38f7e6 to [surge.sh](https://Assembless-assembless-tech-pullrequest-pr-7.surge.sh) ... [Build logs](https://github.com/Assembless/assembless.tech/runs/1914639117)

<a href="https://github.com/Assembless/assembless.tech/runs/1914639117"></a>

<sub>🤖 By [surge-preview](https://github.com/afc163/surge-preview)</sub>

**Comment by DRFR0ST** [comment]
[Lighthouse](https://developers.google.com/web/tools/lighthouse/) report for the changes in this PR:

WPT Profile: threegfast

| Category | Score |
| ------------- | ------------- |
| Performance | 69 | 
| Accessibility | 98 | 
| Best Practices | 86 | 
| SEO | 92 | 
| Progressive Web App | 41 | 


| Measure | Timing |
| ------------- | ------------- |
| First Contentful Paint | 2.6 s | 
| First Meaningful Paint | 2.6 s | 
| Max Potential First Input Delay | 390 ms | 
| Time to Interactive | 7.6 s | 
| First CPU Idle | 7.6 s | 
| Speed Index | 2.5 s | 






_Tested with Lighthouse v5.6.0 via [lighthouse-action](https://github.com/justinribeiro/lighthouse-action)_

**Comment by DRFR0ST** [comment]
[Lighthouse](https://developers.google.com/web/tools/lighthouse/) report for the changes in this PR:

WPT Profile: threegfast

| Category | Score |
| ------------- | ------------- |
| Performance | 69 | 
| Accessibility | 98 | 
| Best Practices | 86 | 
| SEO | 92 | 
| Progressive Web App | 41 | 


| Measure | Timing |
| ------------- | ------------- |
| First Contentful Paint | 2.6 s | 
| First Meaningful Paint | 2.6 s | 
| Max Potential First Input Delay | 380 ms | 
| Time to Interactive | 7.7 s | 
| First CPU Idle | 7.7 s | 
| Speed Index | 2.5 s | 






_Tested with Lighthouse v5.6.0 via [lighthouse-action](https://github.com/justinribeiro/lighthouse-action)_

**Comment by DRFR0ST** [comment]
On mobile, the appbar makes the page horizontally scrollable. Testing on Xiaomi Mi 9T / Android 10.

**Pull request merged**
